# platform :ios, “7.0”
target ‘BaseProject’ do

pod ‘YYKit’
pod 'AFNetworking'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'Masonry'
pod 'IQKeyboardManager'
pod 'KLCPopup'
pod 'TNRadioButtonGroup'
pod 'MJExtension'
end
